// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Room
{

using System;
using FlatBuffers;

public struct KillUnitReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static KillUnitReq GetRootAsKillUnitReq(ByteBuffer _bb) { return GetRootAsKillUnitReq(_bb, new KillUnitReq()); }
  public static KillUnitReq GetRootAsKillUnitReq(ByteBuffer _bb, KillUnitReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public KillUnitReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long AccountUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int ObjectID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<KillUnitReq> CreateKillUnitReq(FlatBufferBuilder builder,
      long accountUID = 0,
      int objectID = 0) {
    builder.StartObject(2);
    KillUnitReq.AddAccountUID(builder, accountUID);
    KillUnitReq.AddObjectID(builder, objectID);
    return KillUnitReq.EndKillUnitReq(builder);
  }

  public static void StartKillUnitReq(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccountUID(FlatBufferBuilder builder, long accountUID) { builder.AddLong(0, accountUID, 0); }
  public static void AddObjectID(FlatBufferBuilder builder, int objectID) { builder.AddInt(1, objectID, 0); }
  public static Offset<KillUnitReq> EndKillUnitReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<KillUnitReq>(o);
  }
};


}
