// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Room
{

using System;
using FlatBuffers;

public struct PlayerLoseReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PlayerLoseReq GetRootAsPlayerLoseReq(ByteBuffer _bb) { return GetRootAsPlayerLoseReq(_bb, new PlayerLoseReq()); }
  public static PlayerLoseReq GetRootAsPlayerLoseReq(ByteBuffer _bb, PlayerLoseReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PlayerLoseReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long AccountUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PlayerIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PlayerLoseReq> CreatePlayerLoseReq(FlatBufferBuilder builder,
      long accountUID = 0,
      int playerIndex = 0) {
    builder.StartObject(2);
    PlayerLoseReq.AddAccountUID(builder, accountUID);
    PlayerLoseReq.AddPlayerIndex(builder, playerIndex);
    return PlayerLoseReq.EndPlayerLoseReq(builder);
  }

  public static void StartPlayerLoseReq(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccountUID(FlatBufferBuilder builder, long accountUID) { builder.AddLong(0, accountUID, 0); }
  public static void AddPlayerIndex(FlatBufferBuilder builder, int playerIndex) { builder.AddInt(1, playerIndex, 0); }
  public static Offset<PlayerLoseReq> EndPlayerLoseReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PlayerLoseReq>(o);
  }
};


}
