// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Login
{

using System;
using FlatBuffers;

public struct LoginAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginAck GetRootAsLoginAck(ByteBuffer _bb) { return GetRootAsLoginAck(_bb, new LoginAck()); }
  public static LoginAck GetRootAsLoginAck(ByteBuffer _bb, LoginAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GameServerID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long AccountUID { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<LoginAck> CreateLoginAck(FlatBufferBuilder builder,
      int result = 0,
      int gameServerID = 0,
      long accountUID = 0) {
    builder.StartObject(3);
    LoginAck.AddAccountUID(builder, accountUID);
    LoginAck.AddGameServerID(builder, gameServerID);
    LoginAck.AddResult(builder, result);
    return LoginAck.EndLoginAck(builder);
  }

  public static void StartLoginAck(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddGameServerID(FlatBufferBuilder builder, int gameServerID) { builder.AddInt(1, gameServerID, 0); }
  public static void AddAccountUID(FlatBufferBuilder builder, long accountUID) { builder.AddLong(2, accountUID, 0); }
  public static Offset<LoginAck> EndLoginAck(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginAck>(o);
  }
};


}
