// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Login
{

using System;
using FlatBuffers;

public struct LoginReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb) { return GetRootAsLoginReq(_bb, new LoginReq()); }
  public static LoginReq GetRootAsLoginReq(ByteBuffer _bb, LoginReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int DeviceType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string UserID { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUserIDBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<LoginReq> CreateLoginReq(FlatBufferBuilder builder,
      int deviceType = 0,
      StringOffset userIDOffset = default(StringOffset)) {
    builder.StartObject(2);
    LoginReq.AddUserID(builder, userIDOffset);
    LoginReq.AddDeviceType(builder, deviceType);
    return LoginReq.EndLoginReq(builder);
  }

  public static void StartLoginReq(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDeviceType(FlatBufferBuilder builder, int deviceType) { builder.AddInt(0, deviceType, 0); }
  public static void AddUserID(FlatBufferBuilder builder, StringOffset userIDOffset) { builder.AddOffset(1, userIDOffset.Value, 0); }
  public static Offset<LoginReq> EndLoginReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginReq>(o);
  }
};


}
