// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS
{

public enum E_ErrorResult : int
{
 INVAILD_USERID = 0,
 INVAILD_ROOM = 1,
 EXPIRE_ROOM = 2,
 NOT_JOIN_ROOM = 3,
 INVAILD_GAME_STATE = 4,
};


}
