// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS
{

public enum E_GameStatus : int
{
 NONE = 0,
 LOADING = 1,
 START = 2,
 PLAYING = 3,
 RESULT = 4,
 END = 5,
};


}
