// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS
{

public enum MessageType : byte
{
 NONE = 0,
 ErrorMsg = 1,
 Login_LoginReq = 2,
 Login_LoginAck = 3,
 Game_GameServerReq = 4,
 Game_GameServerAck = 5,
 Game_GameMatchingReq = 6,
 Game_GameMatchingNotify = 7,
 Game_GameMatchingCancelReq = 8,
 Game_GameMatchingCancelNotify = 9,
 Game_GameReadyReq = 10,
 Game_GameReadyAck = 11,
 Game_GameReadyNotify = 12,
 Game_GameLoadingFinishReq = 13,
 Game_GameLoadingFinishAck = 14,
 Game_GameStartNotify = 15,
 Game_GameStatusNotify = 16,
 Game_GameGiveUpReq = 17,
 Game_GameGiveUpNotify = 18,
 Game_GameEndReq = 19,
 Game_GameEndAck = 20,
 Game_GameEndNotify = 21,
 Room_BuildReq = 22,
 Room_AttackReq = 23,
 Room_UpgradeReq = 24,
 Room_KillUnitReq = 25,
 Room_PlayerLoseReq = 26,
};


}
