// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS
{

using System;
using FlatBuffers;

public struct playerInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static playerInfo GetRootAsplayerInfo(ByteBuffer _bb) { return GetRootAsplayerInfo(_bb, new playerInfo()); }
  public static playerInfo GetRootAsplayerInfo(ByteBuffer _bb, playerInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public playerInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long AccountUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PlayerIdx { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string UserID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUserIDBytes() { return __p.__vector_as_arraysegment(8); }
  public int Point { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<playerInfo> CreateplayerInfo(FlatBufferBuilder builder,
      long accountUID = 0,
      int playerIdx = 0,
      StringOffset userIDOffset = default(StringOffset),
      int point = 0) {
    builder.StartObject(4);
    playerInfo.AddAccountUID(builder, accountUID);
    playerInfo.AddPoint(builder, point);
    playerInfo.AddUserID(builder, userIDOffset);
    playerInfo.AddPlayerIdx(builder, playerIdx);
    return playerInfo.EndplayerInfo(builder);
  }

  public static void StartplayerInfo(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddAccountUID(FlatBufferBuilder builder, long accountUID) { builder.AddLong(0, accountUID, 0); }
  public static void AddPlayerIdx(FlatBufferBuilder builder, int playerIdx) { builder.AddInt(1, playerIdx, 0); }
  public static void AddUserID(FlatBufferBuilder builder, StringOffset userIDOffset) { builder.AddOffset(2, userIDOffset.Value, 0); }
  public static void AddPoint(FlatBufferBuilder builder, int point) { builder.AddInt(3, point, 0); }
  public static Offset<playerInfo> EndplayerInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<playerInfo>(o);
  }
};


}
