// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameGiveUpNotify : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameGiveUpNotify GetRootAsGameGiveUpNotify(ByteBuffer _bb) { return GetRootAsGameGiveUpNotify(_bb, new GameGiveUpNotify()); }
  public static GameGiveUpNotify GetRootAsGameGiveUpNotify(ByteBuffer _bb, GameGiveUpNotify obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameGiveUpNotify __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long AccountUID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<GameGiveUpNotify> CreateGameGiveUpNotify(FlatBufferBuilder builder,
      int result = 0,
      long accountUID = 0) {
    builder.StartObject(2);
    GameGiveUpNotify.AddAccountUID(builder, accountUID);
    GameGiveUpNotify.AddResult(builder, result);
    return GameGiveUpNotify.EndGameGiveUpNotify(builder);
  }

  public static void StartGameGiveUpNotify(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddAccountUID(FlatBufferBuilder builder, long accountUID) { builder.AddLong(1, accountUID, 0); }
  public static Offset<GameGiveUpNotify> EndGameGiveUpNotify(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameGiveUpNotify>(o);
  }
};


}
