// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameLoadingFinishAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameLoadingFinishAck GetRootAsGameLoadingFinishAck(ByteBuffer _bb) { return GetRootAsGameLoadingFinishAck(_bb, new GameLoadingFinishAck()); }
  public static GameLoadingFinishAck GetRootAsGameLoadingFinishAck(ByteBuffer _bb, GameLoadingFinishAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameLoadingFinishAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameLoadingFinishAck> CreateGameLoadingFinishAck(FlatBufferBuilder builder,
      int result = 0) {
    builder.StartObject(1);
    GameLoadingFinishAck.AddResult(builder, result);
    return GameLoadingFinishAck.EndGameLoadingFinishAck(builder);
  }

  public static void StartGameLoadingFinishAck(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static Offset<GameLoadingFinishAck> EndGameLoadingFinishAck(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameLoadingFinishAck>(o);
  }
};


}
