// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameReadyReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameReadyReq GetRootAsGameReadyReq(ByteBuffer _bb) { return GetRootAsGameReadyReq(_bb, new GameReadyReq()); }
  public static GameReadyReq GetRootAsGameReadyReq(ByteBuffer _bb, GameReadyReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameReadyReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RoomUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DeckIdx { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameReadyReq> CreateGameReadyReq(FlatBufferBuilder builder,
      int roomUID = 0,
      int deckIdx = 0) {
    builder.StartObject(2);
    GameReadyReq.AddDeckIdx(builder, deckIdx);
    GameReadyReq.AddRoomUID(builder, roomUID);
    return GameReadyReq.EndGameReadyReq(builder);
  }

  public static void StartGameReadyReq(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddRoomUID(FlatBufferBuilder builder, int roomUID) { builder.AddInt(0, roomUID, 0); }
  public static void AddDeckIdx(FlatBufferBuilder builder, int deckIdx) { builder.AddInt(1, deckIdx, 0); }
  public static Offset<GameReadyReq> EndGameReadyReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameReadyReq>(o);
  }
};


}
