// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameEndAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameEndAck GetRootAsGameEndAck(ByteBuffer _bb) { return GetRootAsGameEndAck(_bb, new GameEndAck()); }
  public static GameEndAck GetRootAsGameEndAck(ByteBuffer _bb, GameEndAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameEndAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BeforePoint { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AfterPoint { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CurrentServerTime { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<GameEndAck> CreateGameEndAck(FlatBufferBuilder builder,
      int result = 0,
      int beforePoint = 0,
      int afterPoint = 0,
      long currentServerTime = 0) {
    builder.StartObject(4);
    GameEndAck.AddCurrentServerTime(builder, currentServerTime);
    GameEndAck.AddAfterPoint(builder, afterPoint);
    GameEndAck.AddBeforePoint(builder, beforePoint);
    GameEndAck.AddResult(builder, result);
    return GameEndAck.EndGameEndAck(builder);
  }

  public static void StartGameEndAck(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddBeforePoint(FlatBufferBuilder builder, int beforePoint) { builder.AddInt(1, beforePoint, 0); }
  public static void AddAfterPoint(FlatBufferBuilder builder, int afterPoint) { builder.AddInt(2, afterPoint, 0); }
  public static void AddCurrentServerTime(FlatBufferBuilder builder, long currentServerTime) { builder.AddLong(3, currentServerTime, 0); }
  public static Offset<GameEndAck> EndGameEndAck(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEndAck>(o);
  }
};


}
