// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameEndReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameEndReq GetRootAsGameEndReq(ByteBuffer _bb) { return GetRootAsGameEndReq(_bb, new GameEndReq()); }
  public static GameEndReq GetRootAsGameEndReq(ByteBuffer _bb, GameEndReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameEndReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int GameResult { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameEndReq> CreateGameEndReq(FlatBufferBuilder builder,
      int gameResult = 0) {
    builder.StartObject(1);
    GameEndReq.AddGameResult(builder, gameResult);
    return GameEndReq.EndGameEndReq(builder);
  }

  public static void StartGameEndReq(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddGameResult(FlatBufferBuilder builder, int gameResult) { builder.AddInt(0, gameResult, 0); }
  public static Offset<GameEndReq> EndGameEndReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameEndReq>(o);
  }
};


}
