// automatically generated by the FlatBuffers compiler, do not modify

namespace ProtocolCS.Game
{

using System;
using FlatBuffers;

public struct GameGiveUpReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameGiveUpReq GetRootAsGameGiveUpReq(ByteBuffer _bb) { return GetRootAsGameGiveUpReq(_bb, new GameGiveUpReq()); }
  public static GameGiveUpReq GetRootAsGameGiveUpReq(ByteBuffer _bb, GameGiveUpReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameGiveUpReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RoomUID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameGiveUpReq> CreateGameGiveUpReq(FlatBufferBuilder builder,
      int roomUID = 0) {
    builder.StartObject(1);
    GameGiveUpReq.AddRoomUID(builder, roomUID);
    return GameGiveUpReq.EndGameGiveUpReq(builder);
  }

  public static void StartGameGiveUpReq(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRoomUID(FlatBufferBuilder builder, int roomUID) { builder.AddInt(0, roomUID, 0); }
  public static Offset<GameGiveUpReq> EndGameGiveUpReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameGiveUpReq>(o);
  }
};


}
